# site settings
title: Vincent Finat-Duclos
subtitle: data visualisation
email: vinz2007@hotmail.com
description: A portfolio of projects I have worked on
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gitvfd.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: Paris
state: 
zip_code: 
country: France
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/gitvfd
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/instavfd
linkedin_url: https://www.linkedin.com/in/vincent-finat-duclos-2198105/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/twitvfd

# build settings
markdown: kramdown

sass:
  style: compressed
